### ISSUE TITLE
EDA: Put two studies from b57 on EDA

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB/MicrobiomeWorkflow#19]
The data for them is ready, just add them to EDA.

**Comment by wbazant** [comment]
https://github.com/VEuPathDB/MicrobiomeWorkflow/blob/master/README.md#what-is-the-workflow-like is a neat doc, I will try to follow it!

**Comment by wbazant** [comment]
STUDY=MORDOR_metatranscriptome
VERSION=20220509
mkdir -p $MD/MicrobiomeStudyEda/$STUDY/$VERSION/{final,fromProvider,workspace}
cp -v /eupath/data/EuPathDB/workflows/MicrobiomeDB/5/data/all_results/*$STUDY*  $MD/MicrobiomeStudyEda/$STUDY/$VERSION/final
cd $MD/MicrobiomeStudyEda/$STUDY/$VERSION/final
rename -v $STUDY $STUDY.WGS *
rename -v .wgs.lineage_abundance.tsv .metaphlan.tsv *

**Comment by wbazant** [comment]
Jie updated the .owl, and I ran this diff command on the results:

```
comm -13 \
  <( $PROJECT_HOME/ApiCommonMetadataRepository/scripts/list_variables_in_metadata_dir.sh  $PROJECT_HOME/ApiCommonMetadataRepository/ISA/metadata/MBSTDY0021/ | tr A-Z a-z | sort ) \
  <( perl $PROJECT_HOME/ApiCommonMetadataRepository/scripts/list_variables_in_owl.pl $PROJECT_HOME/ApiCommonData/Load/ontology/Microbiome/microbiome_human_only.owl | sort ) \
```

I found out I should remove some sample details (env_feature, host_common_name) because they shouldn't be present in the "human only" owl, and also that not all sample details were added to the .owl. I made a list, and updated the ticket.

**Comment by wbazant** [comment]
Got into GUS errors when updating the synonyms table - SResVer.OntologySynonymVer should be made from SRes.OntologySynonym, but since I last did it someone added columns VARIABLE  VARCHAR2(16) and  DISPLAY_ORDER                                      NUMBER to it.I was able to patch it:
```
sqlminus rm41910 <<< 'alter table SResVer.OntologySynonymVer add VARIABLE VARCHAR2(16);'
sqlminus rm41910 <<< 'alter table SResVer.OntologySynonymVer add DISPLAY_ORDER NUMBER;'
```
. I have reset, undid, and restarted:
```
workflowstep -h `pwd` -p % ready
workflow -h `pwd` -r -u beginMicrobiomeOwls
workflow -h `pwd` -r
```

But this still failed, with a following error:
```
DBD::Oracle::st execute failed: ORA-00932: inconsistent datatypes: expected DATE got NUMBER (DBD ERROR: error possibly near <*> indicator at char 48 in 'INSERT INTO SResVer.OntologySynonymVe
r select v.<*>*,1420,SYSDATE,14 from SRes.OntologySynonym v where v.ontology_synonym_id = :p1') [for Statement "INSERT INTO SResVer.OntologySynonymVer select v.*,1420,SYSDATE,14 from SRes.On
tologySynonym v where v.ontology_synonym_id = ?" with ParamValues: :p1='6116'] at /home/wbazant/gus_home/lib/perl/GUS/ObjRelP/DbiDbHandle.pm line 147.
```

**Comment by wbazant** [comment]
I decided to drop everything and rebuild - the command is in the readme. I got additional priviledge failures there:
```

SQL>
SQL> ALTER TABLE EDA_UD.study
  2  ADD (CONSTRAINT edastd_fk FOREIGN KEY (user_dataset_id)
  3  REFERENCES apidbUserDatasets.InstalledUserDataset);
REFERENCES apidbUserDatasets.InstalledUserDataset)
                             *
ERROR at line 3:
ORA-01031: insufficient privileges
```

**Comment by wbazant** [comment]
They were actually eda_ud's priviledges, not mine - JohnI helped me figure out how to fix this one.

**Comment by wbazant** [comment]
I got to the point in the workflow where the sample detail files are being added again, and got failures about sample details still missing. I ran a diff, and found that Jie didn't actually add four of the sample details I asked for - I should have checked earlier! I've updated the ticket, and told Jie.

**Comment by wbazant** [comment]
Got my third .owl update, ran a diff straight away, and it looks good this time, the only unmapped sample detail headers are these:
malaysia_helminth.txt::env_feature
malaysia_helminth.txt::host_common_name
mordor_metatranscriptome.txt::env_feature
mordor_metatranscriptome.txt::host_common_name
and I'm supposed to take them out - they're implied by the choice of the owl for human studies, and the source being a "Participant".

 I started an undo of the workflow (which otherwise seems to have completed successfully) with `workflow -h `pwd` -r -u beginMicrobiomeOwls` so that it undoes itself while I work on the sample detail files.
 
See "Summarise file contents" in the readme, the command is:
 ```
$PROJECT_HOME/ApiCommonMetadataRepository/scripts/summarise_ISA.pl $file $owl
```
and I made a diff before and after. Also, I've put the commands I used in the git commit message.

**Comment by wbazant** [comment]
I got an error when loading the files again. This is because I undid `beginMicrobiomeOwls`, but not the step to copy the manual delivery files - `MicrobiomeStudy_${study}_copyManualDeliveryAndInvestigationFiles` - my mistake!

Then I got an error when undoing:
```
DBD::Oracle::st execute failed: ORA-02292: integrity constraint (EDA.SYS_C00358620) violated - child record found (DBD ERROR: OCIStmtExecute) [for Statement "      delete
      from SRes.ExternalDatabaseRelease
      where row_alg_invocation_id in (43)
        and rownum <= 100000
"] at /home/wbazant/gus_home/lib/perl/GUS/Community/Plugin/Undo.pm line 222.
```

**Comment by wbazant** [comment]
The above error was due to me not running the "GUS::Community::Plugin::Undo" plugin. To run all the undos ever needed, I go through the log file, find the "AlgInvocationId"s mentioned, and run the undos:
```
perl -nE 'm{AlgInvocationId     (.*)} and say $1' steps/MicrobiomeStudyEDA_${study}_RSRC_insertEntityGraph/step.err \
    | xargs -n1 ga GUS::Community::Plugin::Undo --plugin ApiCommonData::Load::Plugin::MBioInsertEntityGraph --workflowContext --commit --algInvocationId
```

This fixed the error. I'm glad, becuase I was already thinking about dropping + recreating from scratch a third time!

**Comment by wbazant** [comment]
The MORDOR study went in, but the Malaysia study had an error I didn't really understand:
```
ERROR:
Characteristic qualifier parent ENTITY does not have a corresponding node. Keys: cultural group at /home/wbazant/gus_home/lib/perl/ApiCommonData/Load/Plugin/MBioInsertEntityGraph.pm line 102, <$fileHandle> line 2.
```

I grabbed the `ga` command from the log file to be to run it without the workflow, removed the --commit flag, and changed --dieOnFirstError 1 to --dieOnFirstError 0 to get all the errors.

only-insert.sh
```
#!/bin/bash 
_term() { 
  echo "Caught SIGINT signal!"  
  kill -TERM "$child" 2>/dev/null 
} 
 
trap _term SIGINT 

ga ApiCommonData::Load::Plugin::MBioInsertEntityGraph --workflowstepid 83 --investigationFile /eupath/data/EuPathDB/devWorkflows/MicrobiomeDB/EDAwg/data/MicrobiomeStudyEDA_Malaysia_Helminth_
RSRC/ISA/MBSTDY0021/Malaysia_Helminth.xml --sampleDetailsFile /eupath/data/EuPathDB/devWorkflows/MicrobiomeDB/EDAwg/data/MicrobiomeStudyEDA_Malaysia_Helminth_RSRC/ISA/MBSTDY0021/Malaysia_Hel
minth.txt --ontologyMappingFile /eupath/data/EuPathDB/devWorkflows/MicrobiomeDB/EDAwg/data/OntologyTerm_microbiome_human_only_RSRC/microbiome_human_only.owl --mbioResultsDir /eupath/data/EuP
athDB/devWorkflows/MicrobiomeDB/EDAwg/data/MicrobiomeStudyEDA_Malaysia_Helminth_RSRC/results --mbioResultsFileExtensions '{ampliconTaxa => "lineage_abundance.tsv", wgsTaxa => "metaphlan.tsv"
, level4ECs => "level4ec.tsv", pathwayAbundances => "pathway_abundance.tsv", pathwayCoverages => "pathway_coverage.tsv", eukdetectCpms => "eukdetect.lineage_abundance.tsv" }' --extDbRlsSpec 
'MicrobiomeStudyEDA_Malaysia_Helminth_RSRC|20220509' --schema EDA  --dieOnFirstError 0 &

child=$!
wait "$child"
```

**Comment by wbazant** [comment]
Didn't help so a debbuger was next. I removed the trap/wait parts, changed `ga` to `perl -d $( which ga )` , and continued to the error.

**Comment by wbazant** [comment]
The error was happening in CBIL::ISA::InvestigationSimple::addNodesAndEdgesToStudy so I looked there.
This was standing out as result of `CBIL::ISA::InvestigationSimple::groupHeadersByOmType` - keyed by ENTITY, whereas the other ones were correctly keyed as "Sample" or "Source":
```
0  HASH(0x3c183b0)
   'ENTITY' => ARRAY(0x14c97db8)
      0  HASH(0x14cd40f0)
         'function' => ARRAY(0xc94e1a8)
              empty array
         'lc_header' => 'cultural group'
         'name' => ARRAY(0xd0187f0)
            0  'malaysia_helminth.txt::cultural group'
         'parent' => 'ENTITY'
         'source_id' => 'OMRSE_00000205'
         'type' => 'characteristicQualifier'
```
Then I noted down it's being returned when I do `$ontologyMapping->{"cultural group"}{characteristicQualifier}` and restarted the workflow to go to the point where we construct the ontology mapping.

In `ApiCommonData::Load::OntologyMapping::getTermsFromOwl` I noticed it does a sparql query called get_column_sourceID , and assigns a parent like this:
```
my $parent = $row->{parent} ? $row->{parent}->as_hash()->{literal} : 'ENTITY';
```
and the sparql query gets the parent from the ISA_2 field like this: `?_entity obo:ISA_2 ?_parent.`.

Then I figured out what was wrong with the .owl: The term OMRSE_00000205::Ethnicity is a term for the variable Malaysia_Helminth.txt::Cultural group, but misses ISA_1 and ISA_2 annotations. I've updated the ticket and assigned back to Jie with this information, asking for another correction of the .owl related to this ticket.

**Comment by wbazant** [comment]
I made a minor foray into what the ISA_2 annotations are for everything, found four terms with multiple ISA_2 annotations and also told Jie about them, and patched my code locally so I don't have to wait for a one line change to the .owl and unload + reload the whole workflow graph, which by this point was only waiting for this one study:
```
diff --git a/Load/lib/perl/OntologyMapping.pm b/Load/lib/perl/OntologyMapping.pm
index 33a74fb07..bc8c79e5f 100644
--- a/Load/lib/perl/OntologyMapping.pm
+++ b/Load/lib/perl/OntologyMapping.pm
@@ -159,7 +159,7 @@ sub getTermsFromOwl {
   my %terms;
   while (my $row = $it->next) {
     my $sid = $row->{iri}->as_hash()->{literal};
-    my $parent = $row->{parent} ? $row->{parent}->as_hash()->{literal} : 'ENTITY';
+    my $parent = $row->{parent} ? $row->{parent}->as_hash()->{literal} : $sid eq "OMRSE_00000205" ? "Source": 'ENTITY';
```

**Comment by wbazant** [comment]
This failed, because of the table "DatasetAttributes.EdaStudyMapping" not existing. I asked around and Dave said Ryan, who was on vacation, added the table.

**Comment by wbazant** [comment]
Actually, John pointed out that this is dataset record attribute query, and it happened because I've rebuilt the site before the tuning manager ( the job https://tm.apidb.org/job/rm41910.dsp). It runs by itself after the presenter changes, but I've triggered the build of the feature site too quickly. Rerunning got rid of the error, but I got a different error:

```
org.gusdb.wdk.model.WdkModelException: Error while resolving attribute query reference "DatasetAttributes.All" in record type "DatasetRecordClasses.DatasetRecordClass"
... 
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
```

**Comment by wbazant** [comment]
This was the missing table:

sqleda <<< 'describe apidbTuning.EupathBuildDates;'
ORA-04043: object apidbTuning.EupathBuildDates does not exist

I noticed that meanwhile, Bindu started running a tuning job:
https://tm.apidb.org/job/rm41910.dsp/167/console

**Comment by wbazant** [comment]
I started a tuning manager build #168, this time with non-default parameters, EupathBuildDates,DatasetPresenter,StudyIdDatasetId. Then John rebuilt the feature site.

**Comment by wbazant** [comment]
The build of the feature site succeeded, but the data's not right for https://feature.microbiomedb.org/ - it still shows "Shannon-indexed alpha diversity data" as a variable, although no data for it (which is good because I took the variable out) and it shows "Data for this study is not currently available." for the two new studies.

**Comment by wbazant** [comment]
I asked and got one hint to try https://feature.microbiomedb.org/mbio.feature/app/reset-session - which removes my cookies - but it didn't really do anything.

**Comment by ryanrdoherty** [comment]
Thought it might be the EDA subsetting cache.  This endpoint will clears it
https://feature.microbiomedb.org/eda/clear-metadata-cache

But I visited that and still get the "Data not available" message.

**Comment by wbazant** [comment]
I think it did something, because now the "Data for this study is not currently available." message also appears on studies I've previously viewed, like DIABIMMUNE!

**Comment by asizemore** [comment]
MORDOR and Malaysia studies appearing on feature site. Closing and moving to complete
